version: '3.8'

services:
  auth:
    build: .
    ports:
      - "9001:9001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/authservice"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
